/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useMemo, useRef } from 'react'
import { useGLTF, PerspectiveCamera, useTexture } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type Formula1Props = {
    bodyColor: string;
    metalColor: string;
    glassColor: string;
    lightColor: string;
    exhaustColor: string;
    tyreTextureURL: string;
    tyreTextureURLs: string[];
    constantWheelSpin?: boolean;
  }

type GLTFResult = GLTF & {
  nodes: {
    Spoiler_Front: THREE.Mesh
    Canard_1: THREE.Mesh
    Canard001: THREE.Mesh
    Front_Spoiler_Holder: THREE.Mesh
    Swan_Neck: THREE.Mesh
    Swan_Neck001: THREE.Mesh
    Spoiler: THREE.Mesh
    Spoiler_Small: THREE.Mesh
    Spoiler_Big: THREE.Mesh
    Spoiler_DRS: THREE.Mesh
    DOWN_CANARD: THREE.Mesh
    DOWN_CANARD_2: THREE.Mesh
    Differential: THREE.Mesh
    Chassis: THREE.Mesh
    Grid: THREE.Mesh
    Body_1: THREE.Mesh
    Body_Back_Wing: THREE.Mesh
    Exhaust: THREE.Mesh
    Lights: THREE.Mesh
    Cabin: THREE.Mesh
    Control: THREE.Mesh
    Seat: THREE.Mesh
    Mirror_1: THREE.Mesh
    Mirror_3: THREE.Mesh
    Mirror_Glass: THREE.Mesh
    Small_Tube: THREE.Mesh
    Big_Tube: THREE.Mesh
    Vertical_Radar_Wing: THREE.Mesh
    Small_Radar_Wing: THREE.Mesh
    Pitot_Tube_Wing: THREE.Mesh
    Horizontal_Radar_wing_2: THREE.Mesh
    Horizontal_Radar_wing_2_1: THREE.Mesh
    Horizontal_Radar_wing_2_2: THREE.Mesh
    Horizontal_Radar_wing_2_3: THREE.Mesh
    Horizontal_Radar_wing_2_5: THREE.Mesh
    ['1']: THREE.Mesh
    ['2']: THREE.Mesh
    ['7']: THREE.Mesh
    ['6']: THREE.Mesh
    ['1_1']: THREE.Mesh
    ['2_1']: THREE.Mesh
    ['7_1']: THREE.Mesh
    ['6_1']: THREE.Mesh
    ['3']: THREE.Mesh
    ['4']: THREE.Mesh
    ['5']: THREE.Mesh
    ['3_1']: THREE.Mesh
    ['4_1']: THREE.Mesh
    ['5_1']: THREE.Mesh
    L_Bujon_Front_Wheel: THREE.Mesh
    L_Inside_Rim_Front: THREE.Mesh
    L_Rim_Front: THREE.Mesh
    L_Front_Tires: THREE.Mesh
    Fender: THREE.Mesh
    Front_Disk: THREE.Mesh
    Tires_Lid_Front: THREE.Mesh
    R_Bujon_Front_Wheel: THREE.Mesh
    R_Inside_Rim_Front: THREE.Mesh
    R_Rim_Front: THREE.Mesh
    R_Front_Tires: THREE.Mesh
    R_Fender: THREE.Mesh
    R_Front_Disk: THREE.Mesh
    R_Tires_Lid_Front: THREE.Mesh
    L_Bujon_Back_Whell: THREE.Mesh
    L_Inside_Rim_Back: THREE.Mesh
    L_Rim_Bck: THREE.Mesh
    L_Back_Tires: THREE.Mesh
    L_Tires_Lid_Back: THREE.Mesh
    R_Bujon_Back_Whell: THREE.Mesh
    R_Inside_Rim_Back: THREE.Mesh
    R_Rim_Bck: THREE.Mesh
    R_Back_Tires: THREE.Mesh
    Tires_Lid_Back: THREE.Mesh
  }
  materials: object
}

export function Formula1(props: Formula1Props) {
  const { nodes } = useGLTF('/honoring_red_bull_racing.gltf') as GLTFResult;

  const wheelRefs = useRef<THREE.Object3D[]>([]);

//   const gripTapeDiffuse = useTexture("/formula1/griptape-diffuse.webp");
//   const gripTapeRoughness = useTexture("/formula1/griptape-roughness.webp");

//   const gripTapeMaterial = useMemo(() => {
//       const material = new THREE.MeshStandardMaterial({
//         map: gripTapeDiffuse,
//         bumpMap: gripTapeRoughness,
//         roughnessMap: gripTapeRoughness,
//         bumpScale: 3.5,
//         roughness: 0.8,
//         color: "#555555",
//       });
  
//       if (gripTapeDiffuse) {
//         gripTapeDiffuse.wrapS = THREE.RepeatWrapping;
//         gripTapeDiffuse.wrapT = THREE.RepeatWrapping;
//         gripTapeDiffuse.repeat.set(9, 9);
//         gripTapeDiffuse.needsUpdate = true;
  
//         gripTapeRoughness.wrapS = THREE.RepeatWrapping;
//         gripTapeRoughness.wrapT = THREE.RepeatWrapping;
//         gripTapeRoughness.repeat.set(9, 9);
//         gripTapeRoughness.needsUpdate = true;
  
//         gripTapeRoughness.anisotropy = 8;
//       }
  
//       return material;
//     }, [gripTapeDiffuse, gripTapeRoughness]);

    //formula1 model props
    // Tyre Textures
  const tyreTextures = useTexture(props.tyreTextureURLs);
  tyreTextures.forEach((texture) => {
    texture.flipY = false;
    texture.colorSpace = THREE.SRGBColorSpace;
  });
  const tyreTextureIndex = props.tyreTextureURLs.findIndex(
    (url) => url === props.tyreTextureURL
  );
  const tyreTexture = tyreTextures[tyreTextureIndex];

  // Metal Normal Map
  const metalNormal = useTexture("/formula1/metal-normal.avif");
  metalNormal.wrapS = THREE.RepeatWrapping;
  metalNormal.wrapT = THREE.RepeatWrapping; 
  metalNormal.anisotropy = 8;
  metalNormal.repeat.set(8, 8);

   // Custom Materials
   const bodyMaterial = useMemo(
    () => new THREE.MeshStandardMaterial({
      color: props.bodyColor,
      metalness: 0.6,
      roughness: 0.2,
      normalMap: metalNormal,
      normalScale: new THREE.Vector2(0.2, 0.2)
    }),
    [props.bodyColor, metalNormal]
  );

  const metalMaterial = useMemo(
    () => new THREE.MeshStandardMaterial({
      color: props.metalColor,
      metalness: 0.9,
      roughness: 0.1,
      normalMap: metalNormal,
      normalScale: new THREE.Vector2(0.4, 0.4)
    }),
    [props.metalColor, metalNormal]
  );

  const glassMaterial = useMemo(
    () => new THREE.MeshPhysicalMaterial({
      color: props.glassColor,
      metalness: 0,
      roughness: 0,
      transmission: 0.9,
      transparent: true,
      opacity: 0.3
    }),
    [props.glassColor]
  );

  const lightMaterial = useMemo(
    () => new THREE.MeshStandardMaterial({
      color: props.lightColor,
      emissive: props.lightColor,
      emissiveIntensity: 0.5,
      roughness: 0.3
    }),
    [props.lightColor]
  );

  const tyreMaterial = useMemo(
    () => new THREE.MeshStandardMaterial({
      map: tyreTexture,
      roughness: 0.8,
      metalness: 0
    }),
    [tyreTexture]
  );

  const exhaustMaterial = useMemo(
    () => new THREE.MeshStandardMaterial({
      color: props.exhaustColor,
      metalness: 0.8,
      roughness: 0.2,
      emissive: '#ff3300',
      emissiveIntensity: 0.2
    }),
    [props.exhaustColor]
  );

  // Add Wheel Refs function
  const addToWheelRefs = (ref: THREE.Object3D | null) => {
    if (ref && !wheelRefs.current.includes(ref)) {
      wheelRefs.current.push(ref);
    }
  };

  // Wheel spinning animation
  useFrame(() => {
    if (!wheelRefs.current || !props.constantWheelSpin) return;
    for (const wheel of wheelRefs.current) {
      wheel.rotation.x += 0.2;
    }
  });

  // One-time spin effect when texture changes
  useEffect(() => {
    if (!wheelRefs.current || props.constantWheelSpin) return;
    for (const wheel of wheelRefs.current) {
      gsap.to(wheel.rotation, {
        x: "-=30",
        duration: 2.5,
        ease: "circ.out",
      });
    }
  }, [props.constantWheelSpin, props.tyreTextureURL]);

  return (
    <group {...props} dispose={null}>
      <group>
        <group scale={0.01}>
          <group name="Scene_1">
            <spotLight
              name="Spot_Light"
              intensity={2.018}
              angle={0.716}
              penumbra={0.4}
              decay={2}
              distance={8685}
              position={[358.429, 492.051, 1150.959]}
              rotation={[1.415, -0.027, -0.281]}>
              <group position={[0, 0, -1]} />
            </spotLight>
            <group
              name="Redbull_F!"
              position={[126.125, -166.252, -356.627]}
              rotation={[0, -0.633, 0]}
              scale={125.435}>
              <group name="SpoilerFront" position={[0.006, -0.491, 5.085]}>
                <mesh
                  name="Spoiler_Front"
                  castShadow
                  receiveShadow
                  geometry={nodes.Spoiler_Front.geometry}
                  material={nodes.Spoiler_Front.material}
                  position={[-0.006, 0.491, -5.085]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <group name="Canard" position={[-0.006, -0.085, -0.432]}>
                  <mesh
                    name="Canard_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Canard_1.geometry}
                    material={nodes.Canard_1.material}
                    position={[0, 0.577, -4.653]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.01}
                  />
                  <mesh
                    name="Canard001"
                    castShadow
                    receiveShadow
                    geometry={nodes.Canard001.geometry}
                    material={nodes.Canard001.material}
                    position={[0, 0.576, -4.653]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.01}
                  />
                </group>
                <mesh
                  name="Front_Spoiler_Holder"
                  castShadow
                  receiveShadow
                  geometry={nodes.Front_Spoiler_Holder.geometry}
                  material={nodes.Front_Spoiler_Holder.material}
                  position={[-0.006, 0.491, -5.085]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
              </group>
              <group name="SpoilerBack" position={[0, 0.377, -2.529]}>
                <group name="swan" position={[0, 0.106, -1.913]}>
                  <mesh
                    name="Swan_Neck"
                    castShadow
                    receiveShadow
                    geometry={nodes.Swan_Neck.geometry}
                    material={nodes.Swan_Neck.material}
                    position={[0, -0.484, 4.441]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.01}
                  />
                  <mesh
                    name="Swan_Neck001"
                    castShadow
                    receiveShadow
                    geometry={nodes.Swan_Neck001.geometry}
                    material={nodes.Swan_Neck001.material}
                    position={[0, -0.484, 4.441]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.01}
                  />
                </group>
                <mesh
                  name="Spoiler"
                  castShadow
                  receiveShadow
                  geometry={nodes.Spoiler.geometry}
                  material={nodes.Spoiler.material}
                  position={[0, 0.377, -2.529]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="Spoiler_Small"
                  castShadow
                  receiveShadow
                  geometry={nodes.Spoiler_Small.geometry}
                  material={nodes.Spoiler_Small.material}
                  position={[0, -0.377, 2.529]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="Spoiler_Big"
                  castShadow
                  receiveShadow
                  geometry={nodes.Spoiler_Big.geometry}
                  material={nodes.Spoiler_Big.material}
                  position={[0, -0.38, 2.529]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="Spoiler_DRS"
                  castShadow
                  receiveShadow
                  geometry={nodes.Spoiler_DRS.geometry}
                  material={nodes.Spoiler_DRS.material}
                  position={[0, -0.377, 2.529]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
              </group>
              <group name="Body" position={[0, 0.081, 0.499]}>
                <group
                  name="DOWN_CANARD_Instance"
                  position={[-0.613, -0.559, -1.966]}
                  scale={[-1, 1, 1]}>
                  <mesh
                    name="DOWN_CANARD"
                    castShadow
                    receiveShadow
                    geometry={nodes.DOWN_CANARD.geometry}
                    material={nodes.DOWN_CANARD.material}
                    position={[-0.613, 0.478, 1.467]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.01}
                  />
                </group>
                <group name="DOWN_CANARD_1" position={[0.613, -0.559, -1.966]}>
                  <mesh
                    name="DOWN_CANARD_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.DOWN_CANARD_2.geometry}
                    material={nodes.DOWN_CANARD_2.material}
                    position={[-0.613, 0.478, 1.467]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.01}
                  />
                </group>
                <mesh
                  name="Differential"
                  castShadow
                  receiveShadow
                  geometry={nodes.Differential.geometry}
                  material={nodes.Differential.material}
                  position={[0, -0.081, -0.499]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="Chassis"
                  castShadow
                  receiveShadow
                  geometry={nodes.Chassis.geometry}
                  material={metalMaterial}
                  position={[0, -0.081, -0.499]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="Grid"
                  castShadow
                  receiveShadow
                  geometry={nodes.Grid.geometry}
                  material={nodes.Grid.material}
                  position={[0, -0.081, -0.499]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="Body_1"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body_1.geometry}
                  material={bodyMaterial}
                  position={[0, -0.081, -0.499]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="Body_Back_Wing"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body_Back_Wing.geometry}
                  material={nodes.Body_Back_Wing.material}
                  position={[0, -0.081, -0.499]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="Exhaust"
                  castShadow
                  receiveShadow
                  geometry={nodes.Exhaust.geometry}
                  material={exhaustMaterial}
                  position={[0, -0.081, -0.322]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="Lights"
                  castShadow
                  receiveShadow
                  geometry={nodes.Lights.geometry}
                  material={lightMaterial}
                  position={[0, -0.081, -0.499]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="Cabin"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cabin.geometry}
                  material={nodes.Cabin.material}
                  position={[0, -0.081, -0.499]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
              </group>
              <group name="Cabin_1" position={[0, 0.174, 1.233]}>
                <mesh
                  name="Control"
                  castShadow
                  receiveShadow
                  geometry={nodes.Control.geometry}
                  material={nodes.Control.material}
                  position={[0, -0.174, -1.233]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="Seat"
                  castShadow
                  receiveShadow
                  geometry={nodes.Seat.geometry}
                  material={nodes.Seat.material}
                  position={[0, -0.174, -1.233]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
              </group>
              <group name="Mirror" position={[0, 0.333, 0.798]}>
                <group name="Mirror_Instance" position={[-0.897, 0, 0]} scale={[-1, 1, 1]}>
                  <mesh
                    name="Mirror_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mirror_1.geometry}
                    material={nodes.Mirror_1.material}
                    position={[-0.897, -0.333, -0.798]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.01}
                  />
                </group>
                <group name="Mirror_2" position={[0.897, 0, 0]}>
                  <mesh
                    name="Mirror_3"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mirror_3.geometry}
                    material={nodes.Mirror_3.material}
                    position={[-0.897, -0.333, -0.798]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.01}
                  />
                </group>
                <mesh
                  name="Mirror_Glass"
                  castShadow
                  receiveShadow
                  geometry={nodes.Mirror_Glass.geometry}
                  material={glassMaterial}
                  position={[0, -0.333, -0.798]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
              </group>
              <group name="Wings" position={[-0.033, 0.546, 1.843]}>
                <mesh
                  name="Small_Tube"
                  castShadow
                  receiveShadow
                  geometry={nodes.Small_Tube.geometry}
                  material={nodes.Small_Tube.material}
                  position={[0.033, -0.546, -1.843]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="Big_Tube"
                  castShadow
                  receiveShadow
                  geometry={nodes.Big_Tube.geometry}
                  material={nodes.Big_Tube.material}
                  position={[0.033, -0.546, -1.843]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="Vertical_Radar_Wing"
                  castShadow
                  receiveShadow
                  geometry={nodes.Vertical_Radar_Wing.geometry}
                  material={nodes.Vertical_Radar_Wing.material}
                  position={[0.033, -0.546, -1.843]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="Small_Radar_Wing"
                  castShadow
                  receiveShadow
                  geometry={nodes.Small_Radar_Wing.geometry}
                  material={nodes.Small_Radar_Wing.material}
                  position={[0.033, -0.546, -1.843]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="Pitot_Tube_Wing"
                  castShadow
                  receiveShadow
                  geometry={nodes.Pitot_Tube_Wing.geometry}
                  material={nodes.Pitot_Tube_Wing.material}
                  position={[0.033, -0.546, -1.843]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <group
                  name="Horizontal_Radar_wing_2_Instance_3"
                  position={[0.03, 0.752, -2.596]}
                  scale={[-1.579, 1, 1]}>
                  <mesh
                    name="Horizontal_Radar_wing_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.Horizontal_Radar_wing_2.geometry}
                    material={nodes.Horizontal_Radar_wing_2.material}
                    position={[-0.325, -0.938, 0.54]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.01}
                  />
                </group>
                <group
                  name="Horizontal_Radar_wing_2_Instance"
                  position={[-0.292, 0.392, -2.383]}
                  scale={[-1, 1, 1]}>
                  <mesh
                    name="Horizontal_Radar_wing_2_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Horizontal_Radar_wing_2_1.geometry}
                    material={nodes.Horizontal_Radar_wing_2_1.material}
                    position={[-0.325, -0.938, 0.54]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.01}
                  />
                </group>
                <group
                  name="Horizontal_Radar_wing_2_Instance_2"
                  position={[-0.422, -0.774, 2.292]}
                  scale={[-1, 1, 0.996]}>
                  <mesh
                    name="Horizontal_Radar_wing_2_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.Horizontal_Radar_wing_2_2.geometry}
                    material={nodes.Horizontal_Radar_wing_2_2.material}
                    position={[-0.325, -0.938, 0.54]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.01}
                  />
                </group>
                <group
                  name="Horizontal_Radar_wing_2_Instance_1"
                  position={[0.491, -0.774, 2.292]}
                  scale={[1, 1, 0.996]}>
                  <mesh
                    name="Horizontal_Radar_wing_2_3"
                    castShadow
                    receiveShadow
                    geometry={nodes.Horizontal_Radar_wing_2_3.geometry}
                    material={nodes.Horizontal_Radar_wing_2_3.material}
                    position={[-0.325, -0.938, 0.54]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.01}
                  />
                </group>
                <group name="Horizontal_Radar_wing_2_4" position={[0.358, 0.392, -2.383]}>
                  <mesh
                    name="Horizontal_Radar_wing_2_5"
                    castShadow
                    receiveShadow
                    geometry={nodes.Horizontal_Radar_wing_2_5.geometry}
                    material={nodes.Horizontal_Radar_wing_2_5.material}
                    position={[-0.325, -0.938, 0.54]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.01}
                  />
                </group>
              </group>
              <group name="SuspBack_Instance" position={[-0.643, -0.193, -3.5]} scale={[-1, 1, 1]}>
                <mesh
                  name="1"
                  castShadow
                  receiveShadow
                  geometry={nodes['1'].geometry}
                  material={nodes['1'].material}
                  position={[-0.644, 0.193, 3.5]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="2"
                  castShadow
                  receiveShadow
                  geometry={nodes['2'].geometry}
                  material={nodes['2'].material}
                  position={[-0.644, 0.193, 3.5]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="7"
                  castShadow
                  receiveShadow
                  geometry={nodes['7'].geometry}
                  material={nodes['7'].material}
                  position={[-0.644, 0.193, 3.5]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="6"
                  castShadow
                  receiveShadow
                  geometry={nodes['6'].geometry}
                  material={nodes['6'].material}
                  position={[-0.644, 0.193, 3.5]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
              </group>
              <group name="SuspBack" position={[0.644, -0.193, -3.5]}>
                <mesh
                  name="1_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['1_1'].geometry}
                  material={nodes['1_1'].material}
                  position={[-0.644, 0.193, 3.5]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="2_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['2_1'].geometry}
                  material={nodes['2_1'].material}
                  position={[-0.644, 0.193, 3.5]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="7_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['7_1'].geometry}
                  material={nodes['7_1'].material}
                  position={[-0.644, 0.193, 3.5]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="6_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['6_1'].geometry}
                  material={nodes['6_1'].material}
                  position={[-0.644, 0.193, 3.5]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
              </group>
              <group
                name="SuspFront_Instance"
                position={[-0.812, -0.233, 3.063]}
                scale={[-1, 1, 1]}>
                <mesh
                  name="3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3'].geometry}
                  material={nodes['3'].material}
                  position={[-0.813, 0.233, -3.063]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="4"
                  castShadow
                  receiveShadow
                  geometry={nodes['4'].geometry}
                  material={nodes['4'].material}
                  position={[-0.813, 0.233, -3.063]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="5"
                  castShadow
                  receiveShadow
                  geometry={nodes['5'].geometry}
                  material={nodes['5'].material}
                  position={[-0.813, 0.233, -3.063]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
              </group>
              <group name="SuspFront" position={[0.813, -0.233, 3.063]}>
                <mesh
                  name="3_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3_1'].geometry}
                  material={nodes['3_1'].material}
                  position={[-0.813, 0.233, -3.063]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="4_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['4_1'].geometry}
                  material={nodes['4_1'].material}
                  position={[-0.813, 0.233, -3.063]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="5_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['5_1'].geometry}
                  material={nodes['5_1'].material}
                  position={[-0.813, 0.233, -3.063]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
              </group>
              <group
                name="L_RimFront_Instance"
                position={[-1.712, -0.353, 3.322]}
                scale={[-1, 1, 1]}>
                <mesh
                  name="L_Bujon_Front_Wheel"
                  castShadow
                  receiveShadow
                  geometry={nodes.L_Bujon_Front_Wheel.geometry}
                  material={nodes.L_Bujon_Front_Wheel.material}
                  position={[-1.713, 0.353, -3.322]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="L_Inside_Rim_Front"
                  castShadow
                  receiveShadow
                  geometry={nodes.L_Inside_Rim_Front.geometry}
                  material={nodes.L_Inside_Rim_Front.material}
                  position={[-1.713, 0.353, -3.322]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="L_Rim_Front"
                  castShadow
                  receiveShadow
                  geometry={nodes.L_Rim_Front.geometry}
                  material={nodes.L_Rim_Front.material}
                  position={[-1.71, 0.353, -3.322]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  ref={addToWheelRefs}
                  name="L_Front_Tires"
                  castShadow
                  receiveShadow
                  geometry={nodes.L_Front_Tires.geometry}
                  material={tyreMaterial}
                  position={[-1.713, 0.353, -3.322]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="Fender"
                  castShadow
                  receiveShadow
                  geometry={nodes.Fender.geometry}
                  material={nodes.Fender.material}
                  position={[-1.71, 0.353, -3.322]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="Front_Disk"
                  castShadow
                  receiveShadow
                  geometry={nodes.Front_Disk.geometry}
                  material={nodes.Front_Disk.material}
                  position={[-1.713, 0.353, -3.322]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="Tires_Lid_Front"
                  castShadow
                  receiveShadow
                  geometry={nodes.Tires_Lid_Front.geometry}
                  material={nodes.Tires_Lid_Front.material}
                  position={[-1.713, 0.353, -3.322]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
              </group>
              <group name="R_RimFront" position={[1.713, -0.353, 3.322]}>
                <mesh
                  name="R_Bujon_Front_Wheel"
                  castShadow
                  receiveShadow
                  geometry={nodes.R_Bujon_Front_Wheel.geometry}
                  material={nodes.R_Bujon_Front_Wheel.material}
                  position={[-1.713, 0.353, -3.322]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="R_Inside_Rim_Front"
                  castShadow
                  receiveShadow
                  geometry={nodes.R_Inside_Rim_Front.geometry}
                  material={nodes.R_Inside_Rim_Front.material}
                  position={[-1.713, 0.353, -3.322]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="R_Rim_Front"
                  castShadow
                  receiveShadow
                  geometry={nodes.R_Rim_Front.geometry}
                  material={nodes.R_Rim_Front.material}
                  position={[-1.71, 0.353, -3.322]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  ref={addToWheelRefs}
                  name="R_Front_Tires"
                  castShadow
                  receiveShadow
                  geometry={nodes.R_Front_Tires.geometry}
                  material={tyreMaterial}
                  position={[-1.713, 0.353, -3.322]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="R_Fender"
                  castShadow
                  receiveShadow
                  geometry={nodes.R_Fender.geometry}
                  material={nodes.R_Fender.material}
                  position={[-1.71, 0.353, -3.322]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="R_Front_Disk"
                  castShadow
                  receiveShadow
                  geometry={nodes.R_Front_Disk.geometry}
                  material={nodes.R_Front_Disk.material}
                  position={[-1.713, 0.353, -3.322]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="R_Tires_Lid_Front"
                  castShadow
                  receiveShadow
                  geometry={nodes.R_Tires_Lid_Front.geometry}
                  material={nodes.R_Tires_Lid_Front.material}
                  position={[-1.713, 0.353, -3.322]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
              </group>
              <group name="L_RimBack_Instance" position={[-1.6, -0.353, -3.871]} scale={[-1, 1, 1]}>
                <mesh
                  name="L_Bujon_Back_Whell"
                  castShadow
                  receiveShadow
                  geometry={nodes.L_Bujon_Back_Whell.geometry}
                  material={nodes.L_Bujon_Back_Whell.material}
                  position={[-1.601, 0.353, 3.871]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="L_Inside_Rim_Back"
                  castShadow
                  receiveShadow
                  geometry={nodes.L_Inside_Rim_Back.geometry}
                  material={nodes.L_Inside_Rim_Back.material}
                  position={[-1.601, 0.353, 3.871]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="L_Rim_Bck"
                  castShadow
                  receiveShadow
                  geometry={nodes.L_Rim_Bck.geometry}
                  material={nodes.L_Rim_Bck.material}
                  position={[-1.601, 0.353, 3.871]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  ref={addToWheelRefs}
                  name="L_Back_Tires"
                  castShadow
                  receiveShadow
                  geometry={nodes.L_Back_Tires.geometry}
                  material={tyreMaterial}
                  position={[-1.601, 0.353, 3.871]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="L_Tires_Lid_Back"
                  castShadow
                  receiveShadow
                  geometry={nodes.L_Tires_Lid_Back.geometry}
                  material={nodes.L_Tires_Lid_Back.material}
                  position={[-1.601, 0.353, 3.871]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
              </group>
              <group name="R_RimBack" position={[1.601, -0.353, -3.871]}>
                <mesh
                  name="R_Bujon_Back_Whell"
                  castShadow
                  receiveShadow
                  geometry={nodes.R_Bujon_Back_Whell.geometry}
                  material={nodes.R_Bujon_Back_Whell.material}
                  position={[-1.601, 0.353, 3.871]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="R_Inside_Rim_Back"
                  castShadow
                  receiveShadow
                  geometry={nodes.R_Inside_Rim_Back.geometry}
                  material={nodes.R_Inside_Rim_Back.material}
                  position={[-1.601, 0.353, 3.871]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="R_Rim_Bck"
                  castShadow
                  receiveShadow
                  geometry={nodes.R_Rim_Bck.geometry}
                  material={nodes.R_Rim_Bck.material}
                  position={[-1.601, 0.353, 3.871]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  ref={addToWheelRefs}
                  name="R_Back_Tires"
                  castShadow
                  receiveShadow
                  geometry={nodes.R_Back_Tires.geometry}
                  material={tyreMaterial}
                  position={[-1.601, 0.353, 3.871]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
                <mesh
                  name="Tires_Lid_Back"
                  castShadow
                  receiveShadow
                  geometry={nodes.Tires_Lid_Back.geometry}
                  material={nodes.Tires_Lid_Back.material}
                  position={[-1.601, 0.353, 3.871]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
              </group>
            </group>
            <PerspectiveCamera
              name="Personal_Camera"
              makeDefault={false}
              far={100000}
              near={70}
              fov={45}
              position={[-375.9, -245.074, 2492.455]}
              rotation={[0.029, -0.168, 0.005]}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/honoring_red_bull_racing.gltf')
